[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_port = /dev/ttyUSB1
monitor_port = /dev/ttyUSB1
monitor_speed = 115200

board_build.arduino.memory_type = qio_opi   ; Enable OPI PSRAM
board_build.partitions = huge_app.csv        ; 3MB app / 1MB SPIFFS
board_upload.flash_size = 8MB
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1

lib_deps =
    zinggjm/GxEPD2@^1.6.8
    adafruit/Adafruit GFX Library@^1.12.6
    bblanchon/ArduinoJson@^7.4.1
